apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets-v2
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: default
      version: 2.13.3
  interval: 5m
  values:
    crd:
      create: true
      keep: false
    keyrenewperiod: '0'
    fullnameOverride: sealed-secrets-v2
    image:
      pullSecrets:
      - registry-credentials
      registry: example.com
      repository: dockerhub/sealed-secrets-controller
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi